apiVersion: v2
name: ecommerce-app
description: Production-grade E-commerce App on Kubernetes with PostgreSQL and Redis
type: application
version: 0.2.0
appVersion: "1.0.0"

keywords:
  - ecommerce
  - nodejs
  - kubernetes
  - helm
  - postgresql
  - redis

maintainers:
  - name: Ayush Harsh
    email: jarsh4ayush85@gmail.com
    url: https://github.com/Ayush-Harsh-devops

dependencies:
  - name: postgresql
    version: "13.2.0"
    repository: https://charts.bitnami.com/bitnami 
    condition: postgresql.enabled
  - name: redis
    version: "18.4.0"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled

annotations:
  category: ecommerce
  licenses: Apache-2.0
